In [16]:
import pandas as pd
from google.colab import drive
pd.set_option('display.max_columns', None)

In [17]:
drive.mount('/content/drive')
df = pd.read_csv('/content/drive/My Drive/Medical_Insurance_Prediction_Project/medical_insurance.csv', encoding ='utf-8')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [18]:
df

,person_id,age,sex,region,urban_rural,income,education,marital_status,employment_status,household_size,dependents,bmi,smoker,alcohol_freq,visits_last_year,hospitalizations_last_3yrs,days_hospitalized_last_3yrs,medication_count,systolic_bp,diastolic_bp,ldl,hba1c,plan_type,network_tier,deductible,copay,policy_term_years,policy_changes_last_2yrs,provider_quality,risk_score,annual_medical_cost,annual_premium,monthly_premium,claims_count,avg_claim_amount,total_claims_paid,chronic_count,hypertension,diabetes,asthma,copd,cardiovascular_disease,cancer_history,kidney_disease,liver_disease,arthritis,mental_health,proc_imaging_count,proc_surgery_count,proc_physio_count,proc_consult_count,proc_lab_count,is_high_risk,had_major_procedure
0,75722,52,Female,North,Suburban,22700.0,Doctorate,Married,Retired,3,1,27.4,Never,NaN,2,0,0,4,121.0,76.0,123.8,5.28,PPO,Bronze,1000,20,4,0,3.73,0.5714,6938.06,876.05,73.00,1,4672.59,4672.59,1,0,0,0,0,0,0,0,0,1,0,1,0,2,0,1,0,0
1,80185,79,Female,North,Urban,12800.0,No HS,Married,Employed,3,1,26.6,Never,Weekly,2,0,0,3,131.0,79.0,97.3,4.82,POS,Gold,1000,10,1,0,3.10,1.0000,1632.61,445.10,37.09,4,297.27,1189.08,2,0,0,0,0,0,0,0,0,1,1,0,0,1,0,1,1,0
2,19865,68,Male,North,Rural,40700.0,HS,Married,Retired,5,3,31.5,Never,NaN,1,0,0,4,160.0,84.0,129.5,5.51,HMO,Platinum,500,20,10,0,3.90,1.0000,7661.01,1538.02,128.17,0,0.00,0.00,3,1,0,0,0,0,1,0,0,0,1,1,0,2,1,0,1,0
3,76700,15,Male,North,Suburban,15600.0,Some College,Married,Self-employed,5,3,31.6,Never,NaN,0,0,0,1,104.0,68.0,160.3,8.50,HMO,Silver,500,20,5,0,3.89,0.2857,5130.27,820.63,68.39,0,0.00,0.00,1,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0
4,92992,53,Male,Central,Suburban,89600.0,Doctorate,Married,Self-employed,2,0,30.5,Never,Daily,3,0,0,2,136.0,83.0,171.0,5.20,POS,Platinum,500,10,7,0,3.90,0.8681,1700.73,500.93,41.74,1,1002.24,1002.24,2,1,0,0,0,0,0,0,0,1,0,2,0,1,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,6266,50,Male,West,Urban,127200.0,No HS,Married,Employed,2,0,28.2,Never,Occasional,0,0,0,1,115.0,74.0,102.5,4.98,PPO,Bronze,500,10,10,0,3.93,0.3516,1295.04,329.32,27.44,0,0.00,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
99996,54887,42,Male,East,Suburban,21600.0,HS,Married,Employed,2,0,27.6,Never,Occasional,0,0,0,1,101.0,66.0,177.1,5.66,PPO,Silver,5000,20,4,0,3.94,0.2637,1451.73,424.21,35.35,0,0.00,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
99997,76821,41,Male,West,Rural,81900.0,HS,Divorced,Unemployed,1,0,29.8,Former,Weekly,7,0,0,1,128.0,83.0,118.8,5.52,PPO,Gold,500,30,9,0,4.14,0.4505,2291.00,534.90,44.58,8,312.56,2500.48,1,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0
99998,861,51,Female,South,Urban,43400.0,Doctorate,Single,Unemployed,3,2,21.9,Never,Occasional,4,0,0,2,110.0,73.0,134.9,5.25,POS,Bronze,2000,20,3,0,2.76,0.5604,1279.76,342.86,28.57,2,552.38,1104.76,1,0,0,0,0,0,0,0,0,0,1,0,0,2,2,1,0,0
99999,15796,44,Female,South,Rural,43700.0,Some College,Married,Employed,2,0,29.2,Never,NaN,1,0,0,0,115.0,72.0,59.5,5.78,PPO,Silver,1000,20,10,0,2.78,0.2857,465.70,265.88,22.16,0,0.00,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 54 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   person_id                    100000 non-null  int64
 1   age                          100000 non-null  int64
 2   sex                          100000 non-null  object
 3   region                       100000 non-null  object
 4   urban_rural                  100000 non-null  object
 5   income                       100000 non-null  float64
 6   education                    100000 non-null  object
 7   marital_status               100000 non-null  object
 8   employment_status            100000 non-null  object
 9   household_size               100000 non-null  int64
 10  dependents                   100000 non-null  int64
 11  bmi                          100000 non-null  float64
 12  smoker                       100000 non-null  object
 13  alcohol_freq                 69917 non-null   object
 14  visits_last_year             100000 non-null  int64
 15  hospitalizations_last_3yrs   100000 non-null  int64
 16  days_hospitalized_last_3yrs  100000 non-null  int64
 17  medication_count             100000 non-null  int64
 18  systolic_bp                  100000 non-null  float64
 19  diastolic_bp                 100000 non-null  float64
 20  ldl                          100000 non-null  float64
 21  hba1c                        100000 non-null  float64
 22  plan_type                    100000 non-null  object
 23  network_tier                 100000 non-null  object
 24  deductible                   100000 non-null  int64
 25  copay                        100000 non-null  int64
 26  policy_term_years            100000 non-null  int64
 27  policy_changes_last_2yrs     100000 non-null  int64
 28  provider_quality             100000 non-null  float64
 29  risk_score                   100000 non-null  float64
 30  annual_medical_cost          100000 non-null  float64
 31  annual_premium               100000 non-null  float64
 32  monthly_premium              100000 non-null  float64
 33  claims_count                 100000 non-null  int64
 34  avg_claim_amount             100000 non-null  float64
 35  total_claims_paid            100000 non-null  float64
 36  chronic_count                100000 non-null  int64
 37  hypertension                 100000 non-null  int64
 38  diabetes                     100000 non-null  int64
 39  asthma                       100000 non-null  int64
 40  copd                         100000 non-null  int64
 41  cardiovascular_disease       100000 non-null  int64
 42  cancer_history               100000 non-null  int64
 43  kidney_disease               100000 non-null  int64
 44  liver_disease                100000 non-null  int64
 45  arthritis                    100000 non-null  int64
 46  mental_health                100000 non-null  int64
 47  proc_imaging_count           100000 non-null  int64
 48  proc_surgery_count           100000 non-null  int64
 49  proc_physio_count            100000 non-null  int64
 50  proc_consult_count           100000 non-null  int64
 51  proc_lab_count               100000 non-null  int64
 52  is_high_risk                 100000 non-null  int64
 53  had_major_procedure          100000 non-null  int64
dtypes: float64(13), int64(31), object(10)
memory usage: 41.2+ MB

In [20]:
df.duplicated().sum()

np.int64(0)

In [21]:
columns_to_drop = ['person_id', 'provider_quality', 'risk_score', 'monthly_premium', 'policy_changes_last_2yrs', 'claims_count', 'avg_claim_amount', 'total_claims_paid', 'chronic_count', 'proc_imaging_count', 'proc_surgery_count', 'proc_physio_count', 'proc_consult_count', 'proc_lab_count', 'is_high_risk']

df_cleaned = df.drop(columns=columns_to_drop)

In [22]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 39 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   age                          100000 non-null  int64
 1   sex                          100000 non-null  object
 2   region                       100000 non-null  object
 3   urban_rural                  100000 non-null  object
 4   income                       100000 non-null  float64
 5   education                    100000 non-null  object
 6   marital_status               100000 non-null  object
 7   employment_status            100000 non-null  object
 8   household_size               100000 non-null  int64
 9   dependents                   100000 non-null  int64
 10  bmi                          100000 non-null  float64
 11  smoker                       100000 non-null  object
 12  alcohol_freq                 69917 non-null   object
 13  visits_last_year             100000 non-null  int64
 14  hospitalizations_last_3yrs   100000 non-null  int64
 15  days_hospitalized_last_3yrs  100000 non-null  int64
 16  medication_count             100000 non-null  int64
 17  systolic_bp                  100000 non-null  float64
 18  diastolic_bp                 100000 non-null  float64
 19  ldl                          100000 non-null  float64
 20  hba1c                        100000 non-null  float64
 21  plan_type                    100000 non-null  object
 22  network_tier                 100000 non-null  object
 23  deductible                   100000 non-null  int64
 24  copay                        100000 non-null  int64
 25  policy_term_years            100000 non-null  int64
 26  annual_medical_cost          100000 non-null  float64
 27  annual_premium               100000 non-null  float64
 28  hypertension                 100000 non-null  int64
 29  diabetes                     100000 non-null  int64
 30  asthma                       100000 non-null  int64
 31  copd                         100000 non-null  int64
 32  cardiovascular_disease       100000 non-null  int64
 33  cancer_history               100000 non-null  int64
 34  kidney_disease               100000 non-null  int64
 35  liver_disease                100000 non-null  int64
 36  arthritis                    100000 non-null  int64
 37  mental_health                100000 non-null  int64
 38  had_major_procedure          100000 non-null  int64
dtypes: float64(8), int64(21), object(10)
memory usage: 29.8+ MB

In [23]:
df_cleaned['alcohol_freq'].unique()

array([nan, 'Weekly', 'Daily', 'Occasional'], dtype=object)

In [24]:
df_cleaned['alcohol_freq'] = df_cleaned['alcohol_freq'].fillna('Never')

In [25]:
df_cleaned['alcohol_freq'].isnull().sum()

np.int64(0)

In [26]:
df_cleaned['alcohol_freq'].unique()

array(['Never', 'Weekly', 'Daily', 'Occasional'], dtype=object)

In [27]:
df_cleaned

,age,sex,region,urban_rural,income,education,marital_status,employment_status,household_size,dependents,bmi,smoker,alcohol_freq,visits_last_year,hospitalizations_last_3yrs,days_hospitalized_last_3yrs,medication_count,systolic_bp,diastolic_bp,ldl,hba1c,plan_type,network_tier,deductible,copay,policy_term_years,annual_medical_cost,annual_premium,hypertension,diabetes,asthma,copd,cardiovascular_disease,cancer_history,kidney_disease,liver_disease,arthritis,mental_health,had_major_procedure
0,52,Female,North,Suburban,22700.0,Doctorate,Married,Retired,3,1,27.4,Never,Never,2,0,0,4,121.0,76.0,123.8,5.28,PPO,Bronze,1000,20,4,6938.06,876.05,0,0,0,0,0,0,0,0,1,0,0
1,79,Female,North,Urban,12800.0,No HS,Married,Employed,3,1,26.6,Never,Weekly,2,0,0,3,131.0,79.0,97.3,4.82,POS,Gold,1000,10,1,1632.61,445.10,0,0,0,0,0,0,0,0,1,1,0
2,68,Male,North,Rural,40700.0,HS,Married,Retired,5,3,31.5,Never,Never,1,0,0,4,160.0,84.0,129.5,5.51,HMO,Platinum,500,20,10,7661.01,1538.02,1,0,0,0,0,1,0,0,0,1,0
3,15,Male,North,Suburban,15600.0,Some College,Married,Self-employed,5,3,31.6,Never,Never,0,0,0,1,104.0,68.0,160.3,8.50,HMO,Silver,500,20,5,5130.27,820.63,0,1,0,0,0,0,0,0,0,0,0
4,53,Male,Central,Suburban,89600.0,Doctorate,Married,Self-employed,2,0,30.5,Never,Daily,3,0,0,2,136.0,83.0,171.0,5.20,POS,Platinum,500,10,7,1700.73,500.93,1,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,50,Male,West,Urban,127200.0,No HS,Married,Employed,2,0,28.2,Never,Occasional,0,0,0,1,115.0,74.0,102.5,4.98,PPO,Bronze,500,10,10,1295.04,329.32,0,0,0,0,0,0,0,0,0,0,0
99996,42,Male,East,Suburban,21600.0,HS,Married,Employed,2,0,27.6,Never,Occasional,0,0,0,1,101.0,66.0,177.1,5.66,PPO,Silver,5000,20,4,1451.73,424.21,0,0,0,0,0,0,0,0,0,0,0
99997,41,Male,West,Rural,81900.0,HS,Divorced,Unemployed,1,0,29.8,Former,Weekly,7,0,0,1,128.0,83.0,118.8,5.52,PPO,Gold,500,30,9,2291.00,534.90,1,0,0,0,0,0,0,0,0,0,0
99998,51,Female,South,Urban,43400.0,Doctorate,Single,Unemployed,3,2,21.9,Never,Occasional,4,0,0,2,110.0,73.0,134.9,5.25,POS,Bronze,2000,20,3,1279.76,342.86,0,0,0,0,0,0,0,0,0,1,0
99999,44,Female,South,Rural,43700.0,Some College,Married,Employed,2,0,29.2,Never,Never,1,0,0,0,115.0,72.0,59.5,5.78,PPO,Silver,1000,20,10,465.70,265.88,0,0,0,0,0,0,0,0,0,0,0

In [29]:
df_cleaned.describe()

,age,income,household_size,dependents,bmi,visits_last_year,hospitalizations_last_3yrs,days_hospitalized_last_3yrs,medication_count,systolic_bp,diastolic_bp,ldl,hba1c,deductible,copay,policy_term_years,annual_medical_cost,annual_premium,hypertension,diabetes,asthma,copd,cardiovascular_disease,cancer_history,kidney_disease,liver_disease,arthritis,mental_health,had_major_procedure
count,100000.000000,1.000000e+05,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,47.521500,4.987390e+04,2.430900,0.898380,26.990512,1.92765,0.093640,0.373350,1.236320,117.808970,73.604770,119.975065,5.605968,1226.725000,19.520400,5.517760,3009.451907,582.320040,0.203450,0.085930,0.058870,0.035950,0.051170,0.021510,0.014620,0.014770,0.108310,0.130140,0.169700
std,15.988752,4.680021e+04,1.075126,0.950654,4.994883,1.73773,0.304848,1.373011,1.209358,15.369187,8.900924,30.262086,0.845996,1019.619375,10.286255,2.868827,3127.462822,399.583722,0.402566,0.280262,0.235382,0.186166,0.220345,0.145078,0.120027,0.120632,0.310773,0.336459,0.375371
min,0.000000,1.100000e+03,1.000000,0.000000,12.000000,0.00000,0.000000,0.000000,0.000000,61.000000,40.000000,30.000000,3.540000,500.000000,10.000000,1.000000,55.550000,211.670000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,37.000000,2.110000e+04,2.000000,0.000000,23.600000,1.00000,0.000000,0.000000,0.000000,107.000000,67.000000,99.400000,5.160000,500.000000,10.000000,3.000000,1175.117500,352.070000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,48.000000,3.620000e+04,2.000000,1.000000,27.000000,2.00000,0.000000,0.000000,1.000000,117.000000,73.000000,120.000000,5.440000,1000.000000,20.000000,6.000000,2082.575000,463.585000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,58.000000,6.220000e+04,3.000000,1.000000,30.400000,3.00000,0.000000,0.000000,2.000000,128.000000,79.000000,140.300000,5.760000,2000.000000,30.000000,8.000000,3707.957500,666.697500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,100.000000,1.061800e+06,9.000000,7.000000,50.400000,25.00000,3.000000,21.000000,11.000000,183.000000,114.000000,248.300000,11.940000,5000.000000,50.000000,10.000000,65724.900000,10962.550000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [30]:
for col in df_cleaned.select_dtypes(include=['object']).columns:
    print(f"Unique values in '{col}': {df_cleaned[col].unique()}")

Unique values in 'sex': ['Female' 'Male' 'Other']
Unique values in 'region': ['North' 'Central' 'West' 'South' 'East']
Unique values in 'urban_rural': ['Suburban' 'Urban' 'Rural']
Unique values in 'education': ['Doctorate' 'No HS' 'HS' 'Some College' 'Masters' 'Bachelors']
Unique values in 'marital_status': ['Married' 'Single' 'Divorced' 'Widowed']
Unique values in 'employment_status': ['Retired' 'Employed' 'Self-employed' 'Unemployed']
Unique values in 'smoker': ['Never' 'Current' 'Former']
Unique values in 'alcohol_freq': ['Never' 'Weekly' 'Daily' 'Occasional']
Unique values in 'plan_type': ['PPO' 'POS' 'HMO' 'EPO']
Unique values in 'network_tier': ['Bronze' 'Gold' 'Platinum' 'Silver']

In [31]:
df_cleaned['education'] = df_cleaned['education'].replace({'No HS': 'High School Dropout', 'HS': 'High School', 'Some College': 'College'})

In [32]:
df_cleaned['plan_type'] = df_cleaned['plan_type'].replace({'PPO': 'Preferred Provider Organization', 'POS': 'Point-of-Service', 'HMO': 'Health Maintenance Organization', 'EPO': 'Exclusive Provider Organization'})

In [33]:
for col in df_cleaned.select_dtypes(include=['object']).columns:
    print(f"Unique values in '{col}': {df_cleaned[col].unique()}")

Unique values in 'sex': ['Female' 'Male' 'Other']
Unique values in 'region': ['North' 'Central' 'West' 'South' 'East']
Unique values in 'urban_rural': ['Suburban' 'Urban' 'Rural']
Unique values in 'education': ['Doctorate' 'High School Dropout' 'High School' 'College' 'Masters'
 'Bachelors']
Unique values in 'marital_status': ['Married' 'Single' 'Divorced' 'Widowed']
Unique values in 'employment_status': ['Retired' 'Employed' 'Self-employed' 'Unemployed']
Unique values in 'smoker': ['Never' 'Current' 'Former']
Unique values in 'alcohol_freq': ['Never' 'Weekly' 'Daily' 'Occasional']
Unique values in 'plan_type': ['Preferred Provider Organization' 'Point-of-Service'
 'Health Maintenance Organization' 'Exclusive Provider Organization']
Unique values in 'network_tier': ['Bronze' 'Gold' 'Platinum' 'Silver']

In [34]:
df_cleaned

,age,sex,region,urban_rural,income,education,marital_status,employment_status,household_size,dependents,bmi,smoker,alcohol_freq,visits_last_year,hospitalizations_last_3yrs,days_hospitalized_last_3yrs,medication_count,systolic_bp,diastolic_bp,ldl,hba1c,plan_type,network_tier,deductible,copay,policy_term_years,annual_medical_cost,annual_premium,hypertension,diabetes,asthma,copd,cardiovascular_disease,cancer_history,kidney_disease,liver_disease,arthritis,mental_health,had_major_procedure
0,52,Female,North,Suburban,22700.0,Doctorate,Married,Retired,3,1,27.4,Never,Never,2,0,0,4,121.0,76.0,123.8,5.28,Preferred Provider Organization,Bronze,1000,20,4,6938.06,876.05,0,0,0,0,0,0,0,0,1,0,0
1,79,Female,North,Urban,12800.0,High School Dropout,Married,Employed,3,1,26.6,Never,Weekly,2,0,0,3,131.0,79.0,97.3,4.82,Point-of-Service,Gold,1000,10,1,1632.61,445.10,0,0,0,0,0,0,0,0,1,1,0
2,68,Male,North,Rural,40700.0,High School,Married,Retired,5,3,31.5,Never,Never,1,0,0,4,160.0,84.0,129.5,5.51,Health Maintenance Organization,Platinum,500,20,10,7661.01,1538.02,1,0,0,0,0,1,0,0,0,1,0
3,15,Male,North,Suburban,15600.0,College,Married,Self-employed,5,3,31.6,Never,Never,0,0,0,1,104.0,68.0,160.3,8.50,Health Maintenance Organization,Silver,500,20,5,5130.27,820.63,0,1,0,0,0,0,0,0,0,0,0
4,53,Male,Central,Suburban,89600.0,Doctorate,Married,Self-employed,2,0,30.5,Never,Daily,3,0,0,2,136.0,83.0,171.0,5.20,Point-of-Service,Platinum,500,10,7,1700.73,500.93,1,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,50,Male,West,Urban,127200.0,High School Dropout,Married,Employed,2,0,28.2,Never,Occasional,0,0,0,1,115.0,74.0,102.5,4.98,Preferred Provider Organization,Bronze,500,10,10,1295.04,329.32,0,0,0,0,0,0,0,0,0,0,0
99996,42,Male,East,Suburban,21600.0,High School,Married,Employed,2,0,27.6,Never,Occasional,0,0,0,1,101.0,66.0,177.1,5.66,Preferred Provider Organization,Silver,5000,20,4,1451.73,424.21,0,0,0,0,0,0,0,0,0,0,0
99997,41,Male,West,Rural,81900.0,High School,Divorced,Unemployed,1,0,29.8,Former,Weekly,7,0,0,1,128.0,83.0,118.8,5.52,Preferred Provider Organization,Gold,500,30,9,2291.00,534.90,1,0,0,0,0,0,0,0,0,0,0
99998,51,Female,South,Urban,43400.0,Doctorate,Single,Unemployed,3,2,21.9,Never,Occasional,4,0,0,2,110.0,73.0,134.9,5.25,Point-of-Service,Bronze,2000,20,3,1279.76,342.86,0,0,0,0,0,0,0,0,0,1,0
99999,44,Female,South,Rural,43700.0,College,Married,Employed,2,0,29.2,Never,Never,1,0,0,0,115.0,72.0,59.5,5.78,Preferred Provider Organization,Silver,1000,20,10,465.70,265.88,0,0,0,0,0,0,0,0,0,0,0

In [35]:
df_cleaned.to_csv('/content/drive/My Drive/Medical_Insurance_Prediction_Project/medical_insurance_cleaned.csv', index = False)