In [1]:
import pandas as pd
from google.colab import drive
pd.set_option('display.max_columns', None)

In [2]:
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
df_cleaned = pd.read_csv('/content/drive/My Drive/Medical_Insurance_Prediction_Project/medical_insurance_cleaned.csv')

In [4]:
df_cleaned

,age,sex,region,urban_rural,income,education,marital_status,employment_status,household_size,dependents,bmi,smoker,alcohol_freq,visits_last_year,hospitalizations_last_3yrs,days_hospitalized_last_3yrs,medication_count,systolic_bp,diastolic_bp,ldl,hba1c,plan_type,network_tier,deductible,copay,policy_term_years,annual_medical_cost,annual_premium,hypertension,diabetes,asthma,copd,cardiovascular_disease,cancer_history,kidney_disease,liver_disease,arthritis,mental_health,had_major_procedure
0,52,Female,North,Suburban,22700.0,Doctorate,Married,Retired,3,1,27.4,Never,Never,2,0,0,4,121.0,76.0,123.8,5.28,Preferred Provider Organization,Bronze,1000,20,4,6938.06,876.05,0,0,0,0,0,0,0,0,1,0,0
1,79,Female,North,Urban,12800.0,High School Dropout,Married,Employed,3,1,26.6,Never,Weekly,2,0,0,3,131.0,79.0,97.3,4.82,Point-of-Service,Gold,1000,10,1,1632.61,445.10,0,0,0,0,0,0,0,0,1,1,0
2,68,Male,North,Rural,40700.0,High School,Married,Retired,5,3,31.5,Never,Never,1,0,0,4,160.0,84.0,129.5,5.51,Health Maintenance Organization,Platinum,500,20,10,7661.01,1538.02,1,0,0,0,0,1,0,0,0,1,0
3,15,Male,North,Suburban,15600.0,College,Married,Self-employed,5,3,31.6,Never,Never,0,0,0,1,104.0,68.0,160.3,8.50,Health Maintenance Organization,Silver,500,20,5,5130.27,820.63,0,1,0,0,0,0,0,0,0,0,0
4,53,Male,Central,Suburban,89600.0,Doctorate,Married,Self-employed,2,0,30.5,Never,Daily,3,0,0,2,136.0,83.0,171.0,5.20,Point-of-Service,Platinum,500,10,7,1700.73,500.93,1,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,50,Male,West,Urban,127200.0,High School Dropout,Married,Employed,2,0,28.2,Never,Occasional,0,0,0,1,115.0,74.0,102.5,4.98,Preferred Provider Organization,Bronze,500,10,10,1295.04,329.32,0,0,0,0,0,0,0,0,0,0,0
99996,42,Male,East,Suburban,21600.0,High School,Married,Employed,2,0,27.6,Never,Occasional,0,0,0,1,101.0,66.0,177.1,5.66,Preferred Provider Organization,Silver,5000,20,4,1451.73,424.21,0,0,0,0,0,0,0,0,0,0,0
99997,41,Male,West,Rural,81900.0,High School,Divorced,Unemployed,1,0,29.8,Former,Weekly,7,0,0,1,128.0,83.0,118.8,5.52,Preferred Provider Organization,Gold,500,30,9,2291.00,534.90,1,0,0,0,0,0,0,0,0,0,0
99998,51,Female,South,Urban,43400.0,Doctorate,Single,Unemployed,3,2,21.9,Never,Occasional,4,0,0,2,110.0,73.0,134.9,5.25,Point-of-Service,Bronze,2000,20,3,1279.76,342.86,0,0,0,0,0,0,0,0,0,1,0
99999,44,Female,South,Rural,43700.0,College,Married,Employed,2,0,29.2,Never,Never,1,0,0,0,115.0,72.0,59.5,5.78,Preferred Provider Organization,Silver,1000,20,10,465.70,265.88,0,0,0,0,0,0,0,0,0,0,0

In [5]:
import numpy as np

# Define the updated conditions for each blood pressure category, with 'Low Blood Pressure' first
conditions = [
    (df_cleaned['systolic_bp'] <= 90) | (df_cleaned['diastolic_bp'] <= 60),
    (df_cleaned['systolic_bp'] < 120) & (df_cleaned['diastolic_bp'] < 80),
    (df_cleaned['systolic_bp'] >= 120) & (df_cleaned['systolic_bp'] <= 129) & (df_cleaned['diastolic_bp'] < 80),
    ((df_cleaned['systolic_bp'] >= 130) & (df_cleaned['systolic_bp'] <= 139)) | ((df_cleaned['diastolic_bp'] >= 80) & (df_cleaned['diastolic_bp'] <= 89)),
    (df_cleaned['systolic_bp'] >= 140) | (df_cleaned['diastolic_bp'] >= 90)
]

# Define the corresponding choices for each category in the correct order
choices = ['Low Blood Pressure', 'Normal', 'Elevated', 'Hypertension Stage 1', 'Hypertension Stage 2']

# Update the 'bp_category' column using np.select
df_cleaned['bp_category'] = np.select(conditions, choices, default='Unknown')

In [6]:
import numpy as np

# Define bin edges and labels for 'bmi'
bmi_bins = [0, 18.5, 25, 30, 35, 40, float('inf')]
bmi_labels = ['Underweight', 'Normal', 'Overweight', 'Obese I', 'Obese II', 'Obese III']
df_cleaned['bmi_group'] = pd.cut(df_cleaned['bmi'], bins=bmi_bins, labels=bmi_labels, right=False)

In [7]:
import numpy as np

# Define bin edges and labels for 'ldl'
ldl_bins = [0, 100, 130, 160, 190, np.inf]
ldl_labels = ['Optimal', 'Near Optimal', 'Borderline High', 'High', 'Very High']
df_cleaned['ldl_group'] = pd.cut(df_cleaned['ldl'], bins=ldl_bins, labels=ldl_labels, right=False)

# Define bin edges and labels for 'hba1c'
hba1c_bins = [0, 5.7, 6.5, np.inf]
hba1c_labels = ['Normal', 'Prediabetes', 'Diabetes']
df_cleaned['hba1c_group'] = pd.cut(df_cleaned['hba1c'], bins=hba1c_bins, labels=hba1c_labels, right=False)

In [8]:
import numpy as np

# Define bin edges and labels for 'annual_premium'
annual_premium_bins = [0, 500, 2000, 5000, 10000, np.inf]
annual_premium_labels = ['Very Low', 'Low', 'Medium', 'High', 'Very High']
df_cleaned['annual_medical_cost_grouped'] = pd.cut(df_cleaned['annual_premium'], bins=annual_premium_bins, labels=annual_premium_labels, right=False)

In [9]:
df_cleaned

,age,sex,region,urban_rural,income,education,marital_status,employment_status,household_size,dependents,bmi,smoker,alcohol_freq,visits_last_year,hospitalizations_last_3yrs,days_hospitalized_last_3yrs,medication_count,systolic_bp,diastolic_bp,ldl,hba1c,plan_type,network_tier,deductible,copay,policy_term_years,annual_medical_cost,annual_premium,hypertension,diabetes,asthma,copd,cardiovascular_disease,cancer_history,kidney_disease,liver_disease,arthritis,mental_health,had_major_procedure,bp_category,bmi_group,ldl_group,hba1c_group,annual_medical_cost_grouped
0,52,Female,North,Suburban,22700.0,Doctorate,Married,Retired,3,1,27.4,Never,Never,2,0,0,4,121.0,76.0,123.8,5.28,Preferred Provider Organization,Bronze,1000,20,4,6938.06,876.05,0,0,0,0,0,0,0,0,1,0,0,Elevated,Overweight,Near Optimal,Normal,Low
1,79,Female,North,Urban,12800.0,High School Dropout,Married,Employed,3,1,26.6,Never,Weekly,2,0,0,3,131.0,79.0,97.3,4.82,Point-of-Service,Gold,1000,10,1,1632.61,445.10,0,0,0,0,0,0,0,0,1,1,0,Hypertension Stage 1,Overweight,Optimal,Normal,Very Low
2,68,Male,North,Rural,40700.0,High School,Married,Retired,5,3,31.5,Never,Never,1,0,0,4,160.0,84.0,129.5,5.51,Health Maintenance Organization,Platinum,500,20,10,7661.01,1538.02,1,0,0,0,0,1,0,0,0,1,0,Hypertension Stage 1,Obese I,Near Optimal,Normal,Low
3,15,Male,North,Suburban,15600.0,College,Married,Self-employed,5,3,31.6,Never,Never,0,0,0,1,104.0,68.0,160.3,8.50,Health Maintenance Organization,Silver,500,20,5,5130.27,820.63,0,1,0,0,0,0,0,0,0,0,0,Normal,Obese I,High,Diabetes,Low
4,53,Male,Central,Suburban,89600.0,Doctorate,Married,Self-employed,2,0,30.5,Never,Daily,3,0,0,2,136.0,83.0,171.0,5.20,Point-of-Service,Platinum,500,10,7,1700.73,500.93,1,0,0,0,0,0,0,0,1,0,0,Hypertension Stage 1,Obese I,High,Normal,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,50,Male,West,Urban,127200.0,High School Dropout,Married,Employed,2,0,28.2,Never,Occasional,0,0,0,1,115.0,74.0,102.5,4.98,Preferred Provider Organization,Bronze,500,10,10,1295.04,329.32,0,0,0,0,0,0,0,0,0,0,0,Normal,Overweight,Near Optimal,Normal,Very Low
99996,42,Male,East,Suburban,21600.0,High School,Married,Employed,2,0,27.6,Never,Occasional,0,0,0,1,101.0,66.0,177.1,5.66,Preferred Provider Organization,Silver,5000,20,4,1451.73,424.21,0,0,0,0,0,0,0,0,0,0,0,Normal,Overweight,High,Normal,Very Low
99997,41,Male,West,Rural,81900.0,High School,Divorced,Unemployed,1,0,29.8,Former,Weekly,7,0,0,1,128.0,83.0,118.8,5.52,Preferred Provider Organization,Gold,500,30,9,2291.00,534.90,1,0,0,0,0,0,0,0,0,0,0,Hypertension Stage 1,Overweight,Near Optimal,Normal,Low
99998,51,Female,South,Urban,43400.0,Doctorate,Single,Unemployed,3,2,21.9,Never,Occasional,4,0,0,2,110.0,73.0,134.9,5.25,Point-of-Service,Bronze,2000,20,3,1279.76,342.86,0,0,0,0,0,0,0,0,0,1,0,Normal,Normal,Borderline High,Normal,Very Low
99999,44,Female,South,Rural,43700.0,College,Married,Employed,2,0,29.2,Never,Never,1,0,0,0,115.0,72.0,59.5,5.78,Preferred Provider Organization,Silver,1000,20,10,465.70,265.88,0,0,0,0,0,0,0,0,0,0,0,Normal,Overweight,Optimal,Prediabetes,Very Low

In [10]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 44 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   age                          100000 non-null  int64
 1   sex                          100000 non-null  object
 2   region                       100000 non-null  object
 3   urban_rural                  100000 non-null  object
 4   income                       100000 non-null  float64
 5   education                    100000 non-null  object
 6   marital_status               100000 non-null  object
 7   employment_status            100000 non-null  object
 8   household_size               100000 non-null  int64
 9   dependents                   100000 non-null  int64
 10  bmi                          100000 non-null  float64
 11  smoker                       100000 non-null  object
 12  alcohol_freq                 100000 non-null  object
 13  visits_last_year             100000 non-null  int64
 14  hospitalizations_last_3yrs   100000 non-null  int64
 15  days_hospitalized_last_3yrs  100000 non-null  int64
 16  medication_count             100000 non-null  int64
 17  systolic_bp                  100000 non-null  float64
 18  diastolic_bp                 100000 non-null  float64
 19  ldl                          100000 non-null  float64
 20  hba1c                        100000 non-null  float64
 21  plan_type                    100000 non-null  object
 22  network_tier                 100000 non-null  object
 23  deductible                   100000 non-null  int64
 24  copay                        100000 non-null  int64
 25  policy_term_years            100000 non-null  int64
 26  annual_medical_cost          100000 non-null  float64
 27  annual_premium               100000 non-null  float64
 28  hypertension                 100000 non-null  int64
 29  diabetes                     100000 non-null  int64
 30  asthma                       100000 non-null  int64
 31  copd                         100000 non-null  int64
 32  cardiovascular_disease       100000 non-null  int64
 33  cancer_history               100000 non-null  int64
 34  kidney_disease               100000 non-null  int64
 35  liver_disease                100000 non-null  int64
 36  arthritis                    100000 non-null  int64
 37  mental_health                100000 non-null  int64
 38  had_major_procedure          100000 non-null  int64
 39  bp_category                  100000 non-null  object
 40  bmi_group                    100000 non-null  category
 41  ldl_group                    100000 non-null  category
 42  hba1c_group                  100000 non-null  category
 43  annual_medical_cost_grouped  100000 non-null  category
dtypes: category(4), float64(8), int64(21), object(11)
memory usage: 30.9+ MB

In [11]:
df_cleaned_engineered = df_cleaned.copy()

In [12]:
df_cleaned_engineered.to_csv('/content/drive/My Drive/Medical_Insurance_Prediction_Project/medical_insurance_cleaned_engineered.csv', index=False)